### ISSUE TITLE
Sample on letting the bot join different channels

### ISSUE THREAD

**Issue by mkpazon** [wooodenleg/TmiK#2]
Does the library allow joining different channels?

Should I have a ` tmi(token = "...", context = this.coroutineContext) { ... }` block for each channel I am joining or can I use the same tmi block?

**Comment by AlcaDesign** [comment]
I don't understand what the code you're showing is, but joining multiple channels is simple. You can add more channels to the`channels` array of the constructor options or just call the `join` method of the client anytime after the connected event.

```js
const client = new tmi.Client({
    channels: [ 'channel_one', 'channel_two' ]
});
```
And/or

```js
client.on('connected', () => {
    client.join(channelName);
});
```

**Comment by filwiesner** [comment]
Hello! Thanks for using my lib @mkpazon 

You can just join another channel with `join("channel")` in any scope.

**Comment by filwiesner** [comment]
I use this function to connect to all the channels I need: 
```kotlin
fun MainScope.joinOnFirstConnect() {
    var first = true

    onConnected {
        val channels = arrayOf("firstChannel", "secondChannel", .... )

        if (first) {
            for (channel in channels)
                join(channel)

            first = false
        }
    }
}
```

**Comment by mkpazon** [comment]
What is the first for?

**Comment by filwiesner** [comment]
Ofcourse you don't have to use this function, it was only demonstration of how can you join multiple channels when connected to Twitch. 

Can this issue be closed now?

**Comment by mkpazon** [comment]
Thanks for the help!
