### ISSUE TITLE
The correct way of handling exceptions in events

### ISSUE THREAD

**Issue by mkpazon** [wooodenleg/TmiK#5]
In my observation, when an exception is encountered say for example `onMessage {...}` the bot crashes. What is the recommended way of handling exceptions such that the bot doesn't crash?

At the moment I use a SupervisorJob to prevent this from happening but I am not sure if there is a better way.

```
onMessage {
   launch(SupervisorJob()) {
       // Exception here
   }
}
```

**Comment by wooodenleg** [comment]
In my opinion this is the desired behavior. When the program encounters exception that is not caught, it should crash.  
You can prevent it by making sure you catch all your exceptions with `try {} catch {}` block just like you would in normal code.  
  
I know this is probably not the answer you were hoping for but the way you are supposed to think about coroutines is that they don't change the way we structure our code. We expect exception - we catch it.  
  
That said, maybe `container` should be Supervisor when I describe it as *closed environment* :thinking:
